basePath: '{{.BasePath}}'
host: '{{.Host}}'
info:
  contact: {}
  description: '{{.Description}}'
  license: {}
  title: '{{.Title}}'
  version: '{{.Version}}'
paths:
  /students/{id}:
    get:
      consumes:
      - application/json
      description: get students by id
      operationId: student id
      parameters:
      - description: Student ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: Student
        "400":
          description: Bad Request
          schema:
            type: interface
        "404":
          description: Not Found
          schema:
            type: interface
        "500":
          description: Server Error
          schema:
            type: interface
      summary: Show student info
      tags:
      - Student
swagger: "2.0"
